[build]
  publish = "_site"
  command = "npm run build"
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; img-src *; media-src *; style-src * 'nonce-inlined-styles'"
    Permissions-Policy = "interest-cohort=()"

[[redirects]]
 from = "/momanddad"
 to = "https://lynneandpaul.surge.sh"
 status = 301

[[redirects]]
  from = "/minecraftexplore/*"
  to = "https://zacs-stuff.netlify.com/minecraftexplore/:splat"
  status = 301
  
[[redirects]]
  from = "/stuff/christmas2012"
  to = "https://zaccolley-christmas2012.glitch.me/"
  status = 301

[[redirects]]
  from = "/stuff/*"
  to = "https://zacs-stuff.netlify.com/:splat"
  status = 301
