[build]
  publish = "_site"
  command = "npm run build"
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; img-src *; media-src *; style-src * 'nonce-inlined-styles'"

[[redirects]]
  from = "https://zaccolley.uk/"
  to = "https://zac.land/"
  status = 301
  force = true

[[redirects]]
  from = "https://zaccolley.uk/*"
  to = "https://zac.land/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "https://zaccolley.co.uk/"
  to = "https://zac.land/"
  status = 301
  force = true

[[redirects]]
  from = "https://zaccolley.co.uk/*"
  to = "https://zac.land/:splat"
  status = 301
  force = true
 
[[redirects]]
  from = "https://zaccolley.com/"
  to = "https://zac.land/"
  status = 301
  force = true

[[redirects]]
  from = "https://zaccolley.com/*"
  to = "https://zac.land/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "https://zaccolley.netlify.com"
  to = "https://zac.land"
  status = 301
  force = true

[[redirects]]
  from = "https://zaccolley.netlify.com/*"
  to = "https://zac.land/:splat"
  status = 301
  force = true

[[redirects]]
 from = "/momanddad"
 to = "https://lynneandpaul.surge.sh"
 status = 301

[[redirects]]
  from = "/minecraftexplore/*"
  to = "https://zacs-stuff.netlify.com/minecraftexplore/:splat"
  status = 301
  
[[redirects]]
  from = "/stuff/christmas2012"
  to = "https://zaccolley-christmas2012.glitch.me/"
  status = 301

[[redirects]]
  from = "/stuff/*"
  to = "https://zacs-stuff.netlify.com/:splat"
  status = 301
